### ISSUE TITLE
Eliminate compiler warnings and turn on -Werr

### ISSUE THREAD

**Issue by ihrwein** [balabit/syslog-ng#776]
I used the master branch.

```
../modules/afprog/afprog.c: In function 'afprogram_reload_store_item_free':
../modules/afprog/afprog.c:69:3: warning: passing argument 1 of 'log_pipe_unref' from incompatible pointer type [enabled by default]
   log_pipe_unref(reload_info->writer);
   ^
In file included from ../lib/driver.h:29:0,
                 from ../modules/afprog/afprog.h:27,
                 from ../modules/afprog/afprog.c:24:
../lib/logpipe.h:237:6: note: expected 'struct LogPipe *' but argument is of type 'struct LogWriter *'
 void log_pipe_unref(LogPipe *self);
      ^
../modules/afprog/afprog.c: In function 'afprogram_dd_kill_child':
../modules/afprog/afprog.c:329:13: warning: unused variable 'pgid' [-Wunused-variable]
       pid_t pgid;
             ^
../modules/afprog/afprog.c: In function 'afprogram_dd_store_reload_store_item':
../modules/afprog/afprog.c:452:3: warning: passing argument 4 of 'cfg_persist_config_add' from incompatible pointer type [enabled by default]
   cfg_persist_config_add(cfg, afprogram_dd_format_persist_name(self), reload_info, afprogram_reload_store_item_destroy_notify, FALSE);
   ^
In file included from ../lib/logpipe.h:30:0,
                 from ../lib/driver.h:29,
                 from ../modules/afprog/afprog.h:27,
                 from ../modules/afprog/afprog.c:24:
../lib/cfg.h:158:6: note: expected 'GDestroyNotify' but argument is of type 'void (*)(struct AFProgramReloadStoreItem *)'
 void cfg_persist_config_add(GlobalConfig *cfg, gchar *name, gpointer value, GDestroyNotify destroy, gboolean force);

```

To do:
- [x] Eliminate compiler warnings - #779
- [ ] Turn on -Werr #871

**Comment by bazsi** [comment]
I saw these too, and this is pretty unfortunate as these are recent
additions.


-- 
Bazsi

**Comment by lbudai** [comment]
ehh... I think we should do something with these warnings :-(
Maybe Travis/drone.io and -Werr could help ... but we are far from that.
(or create a check-warning target in the makefile)

**Comment by bazsi** [comment]
I think the OSE tree is not that far, we only have a handful of warnings,
and half of them is this set. Apart from these we have 5 warnings (2 in
testcases, 2 in the sql destination, and one in the lexer).

```
lib/cfg-lex.c:2246:13: warning: 'yy_fatal_error' defined but not used
[-Wunused-function]
 static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
             ^
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afsql/afsql.c:
In function 'afsql_dd_ensure_initialized_connection':
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afsql/afsql.c:705:3:
warning: 'dbi_conn_new' is deprecated (declared at
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include/dbi/dbi.h:208)
[-Wdeprecated-declarations]
   self->dbi_ctx = dbi_conn_new(self->type);
   ^
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afsql/afsql.c:
In function 'afsql_dd_init':
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afsql/afsql.c:1300:7:
warning: 'dbi_initialize' is deprecated (declared at
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/install/include/dbi/dbi.h:179)
[-Wdeprecated-declarations]
       gint rc = dbi_initialize(NULL);
       ^
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:
In function 'afprogram_reload_store_item_free':
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:69:18:
warning: passing argument 1 of 'log_pipe_unref' from incompatible pointer
type
   log_pipe_unref(reload_info->writer);
                  ^
In file included from
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/driver.h:29:0,
                 from
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.h:27,
                 from
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:24:
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/logpipe.h:237:6:
note: expected 'struct LogPipe *' but argument is of type 'struct LogWriter
*'
 void log_pipe_unref(LogPipe *self);
      ^
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:
In function 'afprogram_dd_kill_child':
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:329:13:
warning: unused variable 'pgid' [-Wunused-variable]
       pid_t pgid;
             ^
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:
In function 'afprogram_dd_store_reload_store_item':
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:452:84:
warning: passing argument 4 of 'cfg_persist_config_add' from incompatible
pointer type
   cfg_persist_config_add(cfg, afprogram_dd_format_persist_name(self),
reload_info, afprogram_reload_store_item_destroy_notify, FALSE);

^
In file included from
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/logpipe.h:30:0,
                 from
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/driver.h:29,
                 from
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.h:27,
                 from
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/afprog/afprog.c:24:
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/cfg.h:158:6:
note: expected 'GDestroyNotify' but argument is of type 'void (*)(struct
AFProgramReloadStoreItem *)'
 void cfg_persist_config_add(GlobalConfig *cfg, gchar *name, gpointer
value, GDestroyNotify destroy, gboolean force);
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/kvformat/tests/test_kv_parser.c:81:1:
warning: ‘assert_kv_parser_fails’ defined but not used [-Wunused-function]
 assert_kv_parser_fails(const gchar *kv)
 ^
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/tests/test_log_message.c:
In function
‘test_log_msg_set_value_indirect_with_self_referencing_handle_results_in_a_nonindirect_value’:
/home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/lib/tests/test_log_message.c:279:12:
warning: unused variable ‘handle’ [-Wunused-variable]
   NVHandle handle;
            ^
```

-- 
Bazsi

**Comment by lbudai** [comment]
Hmm... Then -Werr is a real option.

**Comment by juhaszviktor** [comment]
+1 for the -Werr

**Comment by dnsjts** [comment]
- [ ] Eliminate compiler warnings - #779
- [ ] Turn on -Werr

**Comment by bazsi** [comment]
With the last two branches, syslog-ng should compile warning free with this configuration:
 Features:
  Debug symbols               : yes
  GCC profiling               : no
  Memtrace                    : no
  IPV6 support                : yes
  spoof-source support        : yes
  tcp-wrapper support         : yes
  Linux capability support    : yes
  Env wrapper support         : no
  systemd support             : yes (unit dir: none)
  systemd-journal support     : system
 Modules:
  Module search path          : ${exec_prefix}/lib/syslog-ng
  Sun STREAMS support (module): no
  SQL support (module)        : yes
  PACCT module (EXPERIMENTAL) : no
  MongoDB destination (module): yes
  JSON support (module)       : yes
  SMTP support (module)       : yes
  AMQP destination (module)   : yes
  STOMP destination (module)  : yes
  GEOIP support (module)      : yes
  Redis support (module)      : no
  Riemann destination (module): no
  python                      : yes (pkg-config package: python)
  java                        : no

I am enabling redis/riemann/java to see if they are warning free as well.

**Comment by ihrwein** [comment]
I wanted to turn this on, but I see some warnings in internal ivykis:

```
/bin/bash ../libtool --tag=CC   --mode=link gcc  -Werror   -o iv_event_test iv_event_test.o ../src/libivykis.la
libtool: link: gcc -Werror -o iv_event_test iv_event_test.o  ../src/.libs/libivykis.a
../src/.libs/libivykis.a(iv_main_posix.o): In function `__iv_deinit':
iv_main_posix.c:(.text+0x5a): undefined reference to `pthread_setspecific'
../src/.libs/libivykis.a(iv_main_posix.o): In function `iv_state_destructor':
iv_main_posix.c:(.text+0xaa): undefined reference to `pthread_setspecific'
../src/.libs/libivykis.a(iv_main_posix.o): In function `iv_init':
iv_main_posix.c:(.text+0xe3): undefined reference to `pthread_key_create'
iv_main_posix.c:(.text+0x134): undefined reference to `pthread_setspecific'
../src/.libs/libivykis.a(iv_thread_posix.o): In function `iv_thread_tls_deinit_thread':
iv_thread_posix.c:(.text+0x11b): undefined reference to `pthread_detach'
../src/.libs/libivykis.a(iv_thread_posix.o): In function `iv_thread_handler':
iv_thread_posix.c:(.text+0x229): undefined reference to `__pthread_register_cancel'
iv_thread_posix.c:(.text+0x250): undefined reference to `__pthread_unregister_cancel'
../src/.libs/libivykis.a(iv_thread_posix.o): In function `iv_thread_died':
iv_thread_posix.c:(.text+0x2c6): undefined reference to `pthread_join'
../src/.libs/libivykis.a(iv_thread_posix.o): In function `iv_thread_create':
iv_thread_posix.c:(.text+0x409): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
```

` make CFLAGS="-Werror -pthread"` solves this but I don't want to add `-pthread` to `.travis.yml`.

**Comment by bkil-syslogng** [comment]
I've checked the build log on my own computer, and `make` produces this
line here:

`/bin/bash ../libtool  --tag=CC   --mode=link gcc  -O0 -g -pipe -Wall
-pthread   -o iv_event_test iv_event_test.o ../src/libivykis.la`

Could you elaborate why `-pthread` is missing here?

**Comment by bazsi** [comment]
I can see -pthread on that line.

**Comment by bkil-syslogng** [comment]
@bazsi: Just to elaborate, do you mean on your own computer too? Do you get
any such warnings?

**Comment by bazsi** [comment]
I missed the build output as it was hidden while reading your email on my
phone. Sorry for the confusion. I don't know if I have -pthread on my box
as I don't have access to my computer right now.

On the other hand I do know that ivykis used to use weak symbols on
-lpthread to make that library optional.

**Comment by ihrwein** [comment]
I'll send a PR and we will see what happens on Travis.

**Comment by ihrwein** [comment]
It fails: https://github.com/balabit/syslog-ng/pull/843
